import { StyleSheet, Platform } from "react-native";

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: "#e0f2f1",
  },
  container: {
    padding: Platform.OS === "web" ? 20 : 16,
    maxWidth: Platform.OS === "web" ? 800 : "100%",
    alignSelf: "center",
    width: "100%",
  },
  header: {
    fontSize: Platform.OS === "web" ? 32 : 28,
    fontWeight: "bold",
    marginBottom: 20,
    color: "#1d4ed8",
    textAlign: "center",
    paddingTop: Platform.OS === "web" ? 0 : 10,
  },
  platformInfo: {
    textAlign: "center",
    marginBottom: 30,
    fontSize: 16,
    color: "#064e3b",
    padding: 8,
    borderRadius: 8,
    backgroundColor: "#ccfbf1",
  },
  sectionContainer: {
    marginBottom: 30,
    padding: 15,
    backgroundColor: "#ffffff",
    borderRadius: 12,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 5,
  },
  sectionTitle: {
    fontSize: 22,
    fontWeight: "700",
    color: "#1f2937",
    marginBottom: 5,
    borderBottomWidth: 2,
    borderBottomColor: "#f3f4f6",
    paddingBottom: 5,
  },
  sectionExplanation: {
    fontSize: 14,
    color: "#4b5563",
    marginBottom: 10,
    fontStyle: "italic",
  },
  componentDemo: {
    padding: 10,
    borderWidth: 1,
    borderColor: "#e5e7eb",
    borderRadius: 8,
    alignItems: "center",
  },
  viewDemo: {
    width: 150,
    height: 50,
    backgroundColor: "#38bdf8",
    borderRadius: 8,
    justifyContent: "center",
    alignItems: "center",
  },
  textDemo: {
    fontSize: 18,
    color: "#065f46",
    fontWeight: "600",
  },
  textInputDemo: {
    height: 40,
    borderColor: "#d1d5db",
    borderWidth: 1,
    paddingHorizontal: 10,
    width: "80%",
    borderRadius: 6,
    marginBottom: 8,
    color: "#1f2937",
  },
  pressableDemo: {
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 25,
    elevation: 3,
  },
  pressableText: {
    color: "white",
    fontWeight: "bold",
    textTransform: "uppercase",
  },
  imageDemo: {
    width: 100,
    height: 100,
    borderRadius: 10,
    resizeMode: "cover",
  },
  flatListDemo: {
    width: "100%",
    maxHeight: 200,
  },
  flatListItem: {
    backgroundColor: "#f0f9ff",
    padding: 10,
    marginVertical: 4,
    borderRadius: 6,
    borderLeftWidth: 4,
    borderLeftColor: "#3b82f6",
    width: "100%",
    flexDirection: "row", // 👉 elementos en fila
    justifyContent: "space-between", // 👉 texto a la izq, botón a la der
    alignItems: "center",
  },

  flatListText: {
    fontSize: 14,
    color: "#1f2937",
  },
  modalOverlay: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(0, 0, 0, 0.5)",
  },
  modalContent: {
    margin: 20,
    backgroundColor: "white",
    borderRadius: 20,
    padding: 35,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
    maxWidth: "90%",
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: "bold",
    marginBottom: 15,
    color: "#1f2937",
  },
});
